#!/bin/bash

build() {
	. /etc/default/chkcryptoboot.conf

	touch /tmp/{head,lspci,lsusb,lsblk}.b2sum
	chown root:root /tmp/{head,lspci,lsusb,lsblk}.b2sum
	chmod 600 /tmp/{head,lspci,lsusb,lsblk}.b2sum
	dd if=$BOOTDISK bs=512 count=$SECTORS | b2sum > /tmp/head.b2sum
	lsusb | b2sum > /tmp/lsusb.b2sum
	lspci | b2sum > /tmp/lspci.b2sum
	lsblk -Snrx SERIAL -o MODEL,SERIAL,SIZE,WWN,HCTL,TRAN,SUBSYSTEMS,REV,VENDOR | b2sum > /tmp/lsblk.b2sum

	add_binary "/usr/bin/b2sum"
	add_binary "/usr/bin/lsusb"
	add_binary "/usr/bin/lspci"
	add_binary "/usr/bin/lsblk"
	add_dir "/etc/chkcryptoboot"
	add_file "/etc/default/chkcryptoboot.conf" "/etc/chkcryptoboot/chkcryptoboot.conf"
	add_file "/etc/default/chkcryptoboot-check" "/etc/chkcryptoboot/chkcryptoboot-check"
	add_file "/etc/default/chkcryptoboot.motd" "/etc/chkcryptoboot/chkcryptoboot.motd"
	add_file "/etc/udev/hwdb.bin"
	add_file "/usr/share/hwdata/pci.ids"
	add_file "/usr/share/hwdata/usb.ids"
	add_file "/tmp/head.b2sum" "/etc/chkcryptoboot/head.b2sum"
	add_file "/tmp/lsusb.b2sum" "/etc/chkcryptoboot/lsusb.b2sum"
	add_file "/tmp/lspci.b2sum" "/etc/chkcryptoboot/lspci.b2sum"
	add_file "/tmp/lsblk.b2sum" "/etc/chkcryptoboot/lsblk.b2sum"

	add_file "/usr/lib/systemd/system/chkcryptoboot.service"
	add_file "/etc/systemd/system/chkcryptoboot.service.d/override.conf"
	add_symlink "/usr/lib/systemd/system/cryptsetup.target.wants/chkcryptoboot.service" "/usr/lib/systemd/system/chkcryptoboot.service"
}
