#!/bin/bash

build() {
	. /etc/default/sd-chkcryptoboot.conf

	add_dir "/etc/sd-chkcryptoboot"

	if [ $SECTORS ]; then
		touch /tmp/head.b2sum;
		dd if=/dev/disk/by-id/$BOOTDISKID bs=512 count=$SECTORS | b2sum > /tmp/head.b2sum;
		chown root:root /tmp/head.b2sum;
		chmod 600 /tmp/head.b2sum;
		add_file "/tmp/head.b2sum" "/etc/sd-chkcryptoboot/head.b2sum";
	fi


	if [ $ESPPART ]; then
		touch /tmp/efi.b2sum;
		EFIMOUNT=$(mount | grep $(readlink -f /dev/disk/by-id/$BOOTDISKID-part$ESPPART) | awk '{print 3}')

		if [ ! $EFIMOUNT ]; then
			echo "ERROR: Your ESP is not mounted! Mount ESP and regenerate initrd.";
			exit 1;
		fi

		if [ $EFIPATH ]; then
			dd if=$($EFIMOUNT/$EFIPATH) | b2sum > /tmp/efi.b2sum;
			chown root:root /tmp/efi.b2sum;
			chmod 600 /tmp/efi.b2sum;
			add_file "/tmp/efi.b2sum" "/etc/sd-chkcryptoboot/efi.b2sum";
		else
			dd if=$(/dev/disk/by-id/$BOOTDISKID-part$ESPPART) | b2sum > /tmp/efi.b2sum
			chown root:root /tmp/efi.b2sum;
			chmod 600 /tmp/efi.b2sum;
			add_file "/tmp/efi.b2sum" "/etc/sd-chkcryptoboot/efi.b2sum";
		fi
	fi


	touch /tmp/{lspci,lsusb,lsblk}.b2sum
	chown root:root /tmp/{lspci,lsusb,lsblk}.b2sum
	chmod 600 /tmp/{lspci,lsusb,lsblk}.b2sum

	lsusb | b2sum > /tmp/lsusb.b2sum
	lspci | b2sum > /tmp/lspci.b2sum
	lsblk -Snrx SERIAL -o MODEL,SERIAL,SIZE,WWN,HCTL,TRAN,SUBSYSTEMS,REV,VENDOR | b2sum > /tmp/lsblk.b2sum

	add_binary "/usr/bin/b2sum"
	add_binary "/usr/bin/lsusb"
	add_binary "/usr/bin/lspci"
	add_binary "/usr/bin/lsblk"

	add_file "/etc/default/sd-chkcryptoboot.conf" "/etc/sd-chkcryptoboot/sd-chkcryptoboot.conf"
	add_file "/etc/default/sd-chkcryptoboot-check" "/etc/sd-chkcryptoboot/sd-chkcryptoboot-check"
	add_file "/etc/default/sd-chkcryptoboot.motd" "/etc/sd-chkcryptoboot/sd-chkcryptoboot.motd"
	add_file "/etc/udev/hwdb.bin"
	add_file "/usr/share/hwdata/pci.ids"
	add_file "/usr/share/hwdata/usb.ids"

	add_file "/tmp/lsusb.b2sum" "/etc/sd-chkcryptoboot/lsusb.b2sum"
	add_file "/tmp/lspci.b2sum" "/etc/sd-chkcryptoboot/lspci.b2sum"
	add_file "/tmp/lsblk.b2sum" "/etc/sd-chkcryptoboot/lsblk.b2sum"
	add_file "/usr/lib/systemd/system/sd-chkcryptoboot.service"
	add_file "/etc/systemd/system/sd-chkcryptoboot.service.d/override.conf"
	add_symlink "/usr/lib/systemd/system/cryptsetup.target.wants/sd-chkcryptoboot.service" "/usr/lib/systemd/system/sd-chkcryptoboot.service"
}
