#!/bin/sh

. /etc/chkcryptoboot/chkcryptoboot.conf

cat /etc/chkcryptoboot/chkcryptoboot.motd

ACTUAL=$(dd if=$BOOTDISK bs=512 count=$SECTORS status=none | b2sum)
SAVED=$(cat /etc/chkcryptoboot/head.b2sum)
if test "$ACTUAL" != "$SAVED"; then echo "chkcryptoboot: wrong head.b2sum"; exit 1; fi

ACTUAL=$(lsusb | b2sum)
SAVED=$(cat /etc/chkcryptoboot/lsusb.b2sum)
if test "$ACTUAL" != "$SAVED"; then echo "chkcryptoboot: wrong lsusb.b2sum"; exit 1; fi

ACTUAL=$(lspci | b2sum)
SAVED=$(cat /etc/chkcryptoboot/lspci.b2sum)
if test "$ACTUAL" != "$SAVED"; then echo "chkcryptoboot: wrong lspci.b2sum"; exit 1; fi

ACTUAL=$(lsblk -Snrx SERIAL -o MODEL,SERIAL,SIZE,WWN,HCTL,TRAN,SUBSYSTEMS,REV,VENDOR | b2sum)
SAVED=$(cat /etc/chkcryptoboot/lsblk.b2sum)
if test "$ACTUAL" != "$SAVED"; then echo "chkcryptoboot: wrong lsblk.b2sum"; exit 1; fi

for p in $(cat /proc/cmdline); do
	if test "$p" = "$CMDLINE_NAME=$CMDLINE_VALUE"; then echo "chkcryptoboot: everything nominal"; exit 0; fi
done

echo "chkcryptoboot: wrong cmdline"
exit 2
