#!/bin/sh

. /etc/sd-chkcryptoboot/sd-chkcryptoboot.conf

cat /etc/sd-chkcryptoboot/sd-chkcryptoboot.motd
echo "\n"

if [ $SECTORS ]; then
	ACTUAL=$(dd if=/dev/disk/by-id/$BOOTDISKID bs=512 count=$SECTORS status=none | b2sum);
	SAVED=$(cat /etc/sd-chkcryptoboot/head.b2sum);
	if test "$ACTUAL" != "$SAVED"; then 
		echo "sd-chkcryptoboot: wrong head.b2sum"; exit 1;
	fi
fi

if [ $ESPPART ]; then
	SAVED=$(cat /etc/sd-chkcryptoboot/efi.b2sum);
	mkdir /tmp/efi;
	mount /dev/disk/by-id/$BOOTDISKID-part$ESPPART /tmp/efi;

	if [ $EFIPATH ]; then
		ACTUAL=$(dd if=$(/tmp/efi/$EFIPATH) bs=4M status=none | b2sum);
	else
		ACTUAL=$(dd if=$(/dev/disk/by-id/$BOOTDISKID-part$ESPPART) bs=4M status=none | b2sum);
	fi

	if test "$ACTUAL" != "$SAVED"; then 
		echo "ATTENTION: sd-chkcryptoboot: wrong efi.b2sum";
	fi
	umount /tmp/efi;
fi

ACTUAL=$(lsusb | b2sum)
SAVED=$(cat /etc/sd-chkcryptoboot/lsusb.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkcryptoboot: wrong lsusb.b2sum";
fi

ACTUAL=$(lspci | b2sum)
SAVED=$(cat /etc/sd-chkcryptoboot/lspci.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkcryptoboot: wrong lspci.b2sum";
fi

ACTUAL=$(lsblk -Snrx SERIAL -o MODEL,SERIAL,SIZE,WWN,HCTL,\
TRAN,SUBSYSTEMS,REV,VENDOR | b2sum)
SAVED=$(cat /etc/sd-chkcryptoboot/lsblk.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkcryptoboot: wrong lsblk.b2sum";
fi

for p in $(cat /proc/cmdline); do
	if test "$p" = "$CMDLINE_NAME=$CMDLINE_VALUE"; then 
		echo "sd-chkcryptoboot: everything nominal"; exit 0;
	else
		echo "sd-chkcryptoboot: wrong cmdline"
		exit 2
	fi
done



