#!/bin/sh

. /etc/sd-chkhashboot/sd-chkhashboot.conf

cat /etc/sd-chkhashboot/sd-chkhashboot.motd
echo -e "\n";

if [ $SECTORS ]; then
	ACTUAL=$(dd if=/dev/disk/by-id/$BOOTDISKID bs=512 count=$SECTORS status=none | b2sum);
	SAVED=$(cat /etc/sd-chkhashboot/head.b2sum);
	if test "$ACTUAL" != "$SAVED"; then 
		echo "ATTENTION: sd-chkhashboot: wrong head.b2sum";
	fi
	echo "HEADCHECK: OK";
fi

if [ $ESPPART ]; then
	SAVED=$(cat /etc/sd-chkhashboot/efi.b2sum);
	mkdir /tmp/efi;
	mount /dev/disk/by-id/$BOOTDISKID-part$ESPPART /tmp/efi;

	if [ $EFIPATH ]; then
		ACTUAL=$(dd if=/tmp/efi/$EFIPATH bs=4M status=none | b2sum);
	else
		ACTUAL=$(dd if=/dev/disk/by-id/$BOOTDISKID-part$ESPPART bs=4M status=none | b2sum);
	fi

	if test "$ACTUAL" != "$SAVED"; then 
		echo "ATTENTION: sd-chkhashboot: wrong efi.b2sum";
	fi
	umount /tmp/efi;
	echo "EFICHECK: OK";
fi

ACTUAL=$(lsusb | b2sum)
SAVED=$(cat /etc/sd-chkhashboot/lsusb.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkhashboot: wrong lsusb.b2sum";
fi
echo "USBCHECK: OK";

ACTUAL=$(lspci | b2sum)
SAVED=$(cat /etc/sd-chkhashboot/lspci.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkhashboot: wrong lspci.b2sum";
fi
echo "PCICHECK: OK";

ACTUAL=$(lsblk -Snrx SERIAL -o MODEL,SERIAL,SIZE,WWN,HCTL,\
TRAN,SUBSYSTEMS,REV,VENDOR | b2sum)
SAVED=$(cat /etc/sd-chkhashboot/lsblk.b2sum)
if test "$ACTUAL" != "$SAVED"; then 
	echo "ATTENTION: sd-chkhashboot: wrong lsblk.b2sum";
fi
echo "DISKSCHECK: OK";

for p in $(cat /proc/cmdline); do
	if test "$p" = "$CMDLINE_NAME=$CMDLINE_VALUE"; then
		echo "CMDLINE-CHECK: OK"; exit 0;
	fi
done
echo "ATTENTION: sd-chkhashboot: wrong cmdline"; exit 0
